<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LIN16007873" ignored="0" name="Test" tests="3" failures="1" timestamp="31 Mar 2021 06:41:24 GMT" time="60.45" errors="0">
  <testcase name="validateElements" time="2.441" classname="testCases.Test_script_Test2">
    <failure type="java.lang.AssertionError" message="expected [info@qaclickacademy.coms] but found [info@qaclickacademy.com]">
      <![CDATA[java.lang.AssertionError: expected [info@qaclickacademy.coms] but found [info@qaclickacademy.com]
at testCases.Test_script_Test2.validateElements(Test_script_Test2.java:36)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- validateElements -->
  <testcase name="Login" time="5.429" classname="testCases.Test_script_test1"/>
  <testcase name="Login" time="3.976" classname="testCases.Test_script_test1"/>
</testsuite> <!-- Test -->
